exclude: '.git|.venv|venv|__pycache__|.pytest_cache'

# Specify Python version to use for all hooks
default_language_version:
  python: python3.12

# Custom CI-specific environment variables
ci:
  # Skip mypy hooks in CI due to Python 3.13 compatibility issues
  skip: [mypy]
  # For pre-commit.ci autofix, we can safely run these hooks
  autofix_commit_msg: |
    [pre-commit.ci] Auto fixes from pre-commit hooks

    For more information, see https://pre-commit.ci

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.md$'
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: ["--fix"]
        # Allow E402 (module level import not at top) for specific import patterns needed for Python 3.13+ compatibility
        exclude: |
          (?x)^(
              simplenote_mcp_server\.py|
              run_server\.py|
              run_test_workflow\.py|
              simplenote_mcp/scripts/.*\.py|
              simplenote_mcp/tests/.*\.py
          )$
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: [--config-file=mypy.ini, simplenote_mcp]
        additional_dependencies: [
            "types-requests",
            "types-setuptools",
            "types-PyYAML",
            "pytest",
        ]
