exclude: '.git|.venv|venv|__pycache__|.pytest_cache'

# Custom CI-specific environment variables
ci:
  # Skip mypy and bandit hooks in CI due to Python 3.13 pathlib compatibility issues
  skip: [mypy, bandit]
  # For pre-commit.ci autofix, we can safely run these hooks
  autofix_commit_msg: |
    [pre-commit.ci] Auto fixes from pre-commit hooks
    
    For more information, see https://pre-commit.ci

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.md$'
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: ["--fix"]
        # Allow E402 (module level import not at top) for specific import patterns needed for Python 3.13+ compatibility
        exclude: |
          (?x)^(
              simplenote_mcp_server\.py|
              run_server\.py|
              simplenote_mcp/scripts/.*\.py|
              simplenote_mcp/tests/.*\.py
          )$
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: ["--config-file=mypy.ini"]
        # Apply pathlib patch before running mypy to ensure it works with Python 3.13+
        entry: bash -c 'python simplenote-mcp-server/patch_pathlib.py >/dev/null 2>&1 || true; mypy'
        additional_dependencies: [
            "types-requests",
            "types-setuptools",
            "types-PyYAML",
            "pytest",
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    -   id: bandit
        # Apply pathlib patch before running bandit to ensure it works with Python 3.13+
        entry: bash -c 'python simplenote-mcp-server/patch_pathlib.py >/dev/null 2>&1 || true; bandit'
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
