exclude: '.git|.venv|venv|__pycache__|.pytest_cache'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.md$'
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: ["--config-file=mypy.ini"]
        additional_dependencies: [
            "types-requests",
            "types-setuptools",
            "types-PyYAML",
            "pytest",
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
