# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Copy project files
COPY . .

# Install pip dependencies in editable mode, ignoring scripts since our build doesn't require interactive scripts
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -e .

# Expose any needed ports if applicable (MCP runs over stdio typically, so not required for network ports)

# Run the server using the entrypoint provided by the installed script
ENTRYPOINT ["simplenote-mcp-server"]
