[project]
name = "simplenote-mcp-server"
version = "1.4.0"
description = "A simple MCP Server that connects to Simplenote"
readme = "README.md"
requires-python = ">=3.11, <3.14"
license = { text = "MIT" }
authors = [{ name = "Thomas Juul Dyhr", email = "docdyhr@me.com" }]
dependencies = ["mcp[cli]>=0.4.0", "simplenote>=2.1.4"]

[tool.setuptools.package-data]
"simplenote_mcp" = ["py.typed"]
"simplenote_mcp.server" = ["py.typed"]

[project.optional-dependencies]
dev = [
    "mypy>=1.5.1",
    "ruff>=0.0.284",
    "pre-commit>=3.3.3",
    "bandit>=1.7.5",
    "types-requests",
    "types-setuptools",
    "types-PyYAML",
]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1",
    "pytest-cov>=4.1.0",
]

[project.scripts]
simplenote-mcp-server = "simplenote_mcp.server:run_main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py313"
line-length = 88  # Match Black's default
fix = true  # Attempt to automatically fix violations
unsafe-fixes = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "RUF", # Ruff-specific rules
    "D",   # pydocstyle
]
ignore = ["E203", "E501"]  # Maintain compatibility with Black style

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["ARG001", "ARG002"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["simplenote_mcp"]
combine-as-imports = true

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv", ".git", "__pycache__"]
skips = ["B101", "B104"]
targets = ["simplenote_mcp"]
