name: Auto-Merge PRs

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    permissions:
      pull-requests: write
      contents: write
      checks: read
    uses: ./.github/workflows/reusable-auto-merge-pr.yml

  dependabot-auto-merge:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      contents: write
    uses: ./.github/workflows/reusable-dependabot-auto-merge.yml
    secrets: inherit
