name: Python Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        . .venv/bin/activate
        uv pip install -e .
        uv pip install pytest pytest-cov pytest-asyncio ruff mypy

    - name: Install pre-commit
      run: |
        . .venv/bin/activate
        uv pip install pre-commit
        pre-commit install
        
    - name: Run pre-commit
      continue-on-error: true
      run: |
        . .venv/bin/activate
        pre-commit run --all-files

    - name: Type check with mypy
      run: |
        . .venv/bin/activate
        mypy simplenote_mcp --config-file=mypy.ini

    - name: Test with pytest
      run: |
        . .venv/bin/activate
        pytest --cov=simplenote_mcp --cov-report=xml --cov-report=term tests/
      env:
        SIMPLENOTE_EMAIL: "test@example.com"
        SIMPLENOTE_PASSWORD: "test_password"

    - name: List coverage files
      run: |
        ls -la
        ls -la coverage.xml || echo "coverage.xml not found"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
