name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio pytest-cov pytest-mock
      continue-on-error: false
    
    - name: Verify installation
      run: |
        python -c "import simplenote_mcp; print('✅ Package import successful')"
        echo "✅ Test dependencies installed successfully"
    
    - name: Run unit tests (fast tests only)
      env:
        SIMPLENOTE_EMAIL: "test@example.com"
        SIMPLENOTE_PASSWORD: "test_password"
        SIMPLENOTE_OFFLINE_MODE: "true"
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Run fast unit tests only, excluding integration tests
        pytest tests/ -v \
          --cov=simplenote_mcp \
          --cov-report=xml \
          --cov-report=html \
          --ignore=tests/test_title_search_integration.py \
          --ignore=tests/test_search_integration.py \
          -k "not (integration or real_api or network or slow)" \
          --durations=10
    
    - name: Upload coverage reports
      if: matrix.python-version == '3.12'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff mypy
    
    - name: Verify installation
      run: |
        python -c "import simplenote_mcp; print('✅ Package import successful')"
    
    - name: Lint with ruff
      run: |
        ruff check . || echo "⚠️ Linting issues found but continuing"
      continue-on-error: true
    
    - name: Format check with ruff
      run: |
        ruff format --check . || echo "⚠️ Format issues found but continuing"
      continue-on-error: true
    
    - name: Type check with mypy
      run: |
        mypy simplenote_mcp --config-file=mypy.ini || echo "⚠️ Type checking issues found but continuing"
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-dist-packages
        path: dist/